// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'yrs_array.dart';
import 'yrs_map.dart';
import 'yrs_text.dart';
part 'values.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `any_to_yout`, `out_to_yout`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YOutValue>>
abstract class YOutValue implements RustOpaqueInterface {
  YrsArray? asArray();

  bool? asBool();

  Uint8List? asBytes();

  double? asDouble();

  PlatformInt64? asInt();

  String? asJsonArray();

  String? asJsonMap();

  YrsMap? asMap();

  String? asString();

  YrsText? asText();

  bool isNull();

  YOutKind kind();
}

@freezed
sealed class YInValue with _$YInValue {
  const YInValue._();

  const factory YInValue.string(
    String field0,
  ) = YInValue_String;
  const factory YInValue.int(
    PlatformInt64 field0,
  ) = YInValue_Int;
  const factory YInValue.double(
    double field0,
  ) = YInValue_Double;
  const factory YInValue.bool(
    bool field0,
  ) = YInValue_Bool;
  const factory YInValue.null_() = YInValue_Null;
  const factory YInValue.bytes(
    Uint8List field0,
  ) = YInValue_Bytes;
}

/// Variant tag for [`YOutValue`], returned by [`YOutValue::kind`] so the Dart
/// wrapper can dispatch on the correct accessor in one FFI call instead of
/// probing each `as_*` accessor in sequence.
enum YOutKind {
  string,
  int,
  double,
  bool,
  null_,
  bytes,
  jsonArray,
  jsonMap,
  map,
  array,
  text,
  ;
}
