// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'yrs_array.dart';
import 'yrs_map.dart';
import 'yrs_text.dart';
part 'yrs_doc.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `array_entry`, `container_kind`, `deep_copy`, `insert`, `is_same_map_entry`, `kind`, `label`, `new_with_options`, `path`, `remove`, `resolve_container`, `resolve_root`, `resolve`, `root_kind_label`, `target_descends_into_source`, `validate_source`, `validate_target`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ContainerKind`, `PathContainer`, `ResolvedLocation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YrsDoc>>
abstract class YrsDoc implements RustOpaqueInterface {
  /// Apply a v1-encoded update from a remote peer or storage rehydration.
  /// Tagged with the remote origin so it never enters any active
  /// `YUndoManager`'s undo stack.
  void applyUpdate({required List<int> update});

  /// Release held observer subscriptions. yrs's `Doc` itself is `Arc`-backed
  /// and freed when the last handle drops; this method exists for symmetry
  /// with consumer lifecycle code (e.g. `Bloc.close`).
  void dispose();

  /// Encode operations this doc has that the given `state_vector` does not.
  /// If `state_vector` is `None`, encodes the full state (equivalent to
  /// `save()`).
  Uint8List encodeStateAsUpdate({Uint8List? stateVector});

  /// Reload a document from a previously-saved binary blob.
  static YrsDoc fromBytes({required List<int> blob}) =>
      RustLib.instance.api.crateApiYrsDocYrsDocFromBytes(blob: blob);

  /// Get-or-create a root-level array by name.
  YrsArray getArray({required String name});

  /// Get-or-create a root-level map by name.
  YrsMap getMap({required String name});

  /// Snapshot of the local clock state, encoded as v1 bytes. Send to a peer
  /// who can compute the diff this doc is missing via `encodeStateAsUpdate`.
  Uint8List getStateVector();

  /// Get-or-create a root-level text by name.
  YrsText getText({required String name});

  /// Create a new empty document.
  static YrsDoc newEmpty() =>
      RustLib.instance.api.crateApiYrsDocYrsDocNewEmpty();

  /// Subscribe to v1-encoded update blobs. The `sink` receives one event per
  /// committed transaction. Each blob is consumable by `apply_update` on a
  /// peer doc. The subscription is held for the lifetime of this `YrsDoc`
  /// (or until `dispose()`).
  ///
  /// `#[frb(sync)]` is required: `default_dart_async: false` skips the frb
  /// worker pool, so an async-dispatched call would have no executor.
  Stream<Uint8List> observeUpdates();

  /// Save the document to a binary blob. Symmetric with `from_bytes`.
  Uint8List save();

  /// Move or deep-copy one document entry using one local yrs transaction.
  ///
  /// All paths, container kinds, source existence, target availability,
  /// indexes, and ancestry are validated against that same transaction before
  /// its first write, so a rejected transfer leaves the document byte-identical.
  /// A same-list move to either adjacent insertion gap is a zero-write no-op.
  ///
  /// **A move within one list and a move between lists are not the same
  /// operation.** The first is a real CRDT move; the second is a deep copy plus
  /// a removal, because no cross-parent move exists in yrs or Yjs. The second
  /// therefore discards a peer's concurrent edits to the moved subtree and
  /// invalidates live handles to it. The returned [`YrsTransferOutcome`] says
  /// which happened — inspect it rather than assuming, particularly if remote
  /// peers may be editing the same subtree.
  YrsTransferOutcome transferEntryAtomically(
      {required YrsTransferMode mode,
      required YrsTransferLocation source,
      required YrsTransferLocation target});
}

@freezed
sealed class YrsPathSegment with _$YrsPathSegment {
  const YrsPathSegment._();

  const factory YrsPathSegment.key(
    String field0,
  ) = YrsPathSegment_Key;
  const factory YrsPathSegment.index(
    int field0,
  ) = YrsPathSegment_Index;
}

@freezed
sealed class YrsTransferLocation with _$YrsTransferLocation {
  const YrsTransferLocation._();

  const factory YrsTransferLocation.array({
    required List<YrsPathSegment> path,
    required int index,
  }) = YrsTransferLocation_Array;
  const factory YrsTransferLocation.map({
    required List<YrsPathSegment> path,
    required String key,
  }) = YrsTransferLocation_Map;

  /// Destination-only list slot owned by a map. If [key] is absent, an
  /// array is created inside the same validated transfer transaction. An
  /// existing non-array value is always rejected before the first write.
  const factory YrsTransferLocation.arrayAtMapKey({
    required List<YrsPathSegment> parentPath,
    required String key,
    required int index,
  }) = YrsTransferLocation_ArrayAtMapKey;
}

/// Whether an atomic document transfer removes or preserves its source entry.
enum YrsTransferMode {
  move,
  copy,
  ;
}

/// What an atomic document transfer actually did.
///
/// A transfer has two possible mechanisms, and which one runs is not something
/// the caller chooses — it follows from whether the entry stays under the same
/// parent. The distinction matters for collaboration, so it is reported rather
/// than hidden.
enum YrsTransferOutcome {
  /// Nothing was written: the request was already satisfied. A same-list move
  /// to either adjacent insertion gap, or a move to the map slot the entry
  /// already occupies.
  unchanged,

  /// A real CRDT move within one list. The entry keeps its identity: a peer's
  /// concurrent edits to it survive synchronization, live container handles to
  /// it stay valid, and concurrent peers converge on the move itself.
  moved,

  /// The entry was deep-copied under its new parent and the original removed,
  /// because neither yrs nor Yjs can express a move between different parents
  /// — there is no cross-parent move in the CRDT to fall back on.
  ///
  /// Two consequences follow, and both are visible to users:
  ///
  /// - A peer's edits to the moved subtree made concurrently with the reparent
  ///   are **discarded** once the two sides synchronize. The subtree that
  ///   arrives is a copy of the state this peer saw.
  /// - Container handles held on the source become **invalid**. Reads return
  ///   nothing and writes land on a deleted branch, growing the document
  ///   without producing any visible change.
  ///
  /// A caller that cares should re-resolve handles after a `Reparented`
  /// outcome, and should think about whether reparenting is safe to offer at
  /// all while remote peers may be editing the same subtree.
  reparented,

  /// The entry was deep-copied and the source left in place. The copy is
  /// independent: mutating either side does not affect the other.
  copied,
  ;

  /// Whether the document was modified. `false` only for
  /// [`YrsTransferOutcome::Unchanged`].
  bool changedDocument() =>
      RustLib.instance.api.crateApiYrsDocYrsTransferOutcomeChangedDocument(
        that: this,
      );
}
