// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YrsText>>
abstract class YrsText implements RustOpaqueInterface {
  void insert({required int index, required String chunk});

  /// Length in UTF-16 code units.
  int length();

  void remove({required int index, required int length});

  /// Current string value. Indices are UTF-16 code units (matches Dart strings).
  String value();
}
