// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'values.dart';
import 'yrs_map.dart';
import 'yrs_text.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YrsArray>>
abstract class YrsArray implements RustOpaqueInterface {
  YOutValue? get_({required int index});

  void insert({required int index, required YInValue value});

  YrsArray insertArray({required int index});

  YrsMap insertMap({required int index});

  YrsText insertText({required int index});

  String json();

  int length();

  void push({required YInValue value});

  YrsArray pushArray();

  YrsMap pushMap();

  YrsText pushText();

  void removeAt({required int index});

  void removeRange({required int index, required int length});
}
