// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'yrs_array.dart';
import 'yrs_doc.dart';
import 'yrs_map.dart';
import 'yrs_text.dart';

// These functions are ignored because they are not marked as `pub`: `build_undo_options`, `expand`, `merge_stack_items`, `release_redo_stack`, `replace_manager`, `with_mut`, `with_ref`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CancelableCapture`, `CrossClock`, `UndoState`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `now`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YrsScopeItem>>
abstract class YrsScopeItem implements RustOpaqueInterface {
  static YrsScopeItem fromArray({required YrsArray array}) =>
      RustLib.instance.api.crateApiYrsUndoYrsScopeItemFromArray(array: array);

  static YrsScopeItem fromMap({required YrsMap map}) =>
      RustLib.instance.api.crateApiYrsUndoYrsScopeItemFromMap(map: map);

  static YrsScopeItem fromText({required YrsText text}) =>
      RustLib.instance.api.crateApiYrsUndoYrsScopeItemFromText(text: text);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YrsUndoManager>>
abstract class YrsUndoManager implements RustOpaqueInterface {
  void addScope({required YrsScopeItem item});

  /// Starts one explicitly bounded capture that may later be cancelled.
  ///
  /// Only one capture may be active. The returned identifier must be passed
  /// back to `finishCancelableCapture` or `cancelCancelableCapture`, either of
  /// which always closes the capture and frees the slot. Returning `None`
  /// leaves the manager unchanged.
  BigInt? beginCancelableCapture();

  bool canRedo();

  bool canUndo();

  /// Reverts the whole matching bounded capture and permanently discards the
  /// redo history that reverting it produced.
  ///
  /// The undo depth is walked back to exactly where the capture opened,
  /// however many stack items the session ended up spanning, so the document
  /// returns to its pre-session state. Undo entries older than the capture
  /// remain available, and redo entries that existed before it began are
  /// restored. Only a mismatched/stale identifier or a disposed manager
  /// fails; a live matching capture always closes.
  bool cancelCancelableCapture({required BigInt captureId});

  /// Drop both undo and redo stacks.
  void clear();

  void dispose();

  /// Finishes the matching bounded capture and forces the next mutation to
  /// start a new undo item.
  ///
  /// Whatever the session did — one write, a hundred merged keystrokes, an
  /// undo/redo pair, an explicit `reset()` — everything it pushed above the
  /// depth the capture opened at collapses into the single undoable step a
  /// capture means. Only a mismatched/stale identifier or a disposed manager
  /// fails; a live matching capture always closes.
  bool finishCancelableCapture({required BigInt captureId});

  factory YrsUndoManager(
          {required YrsDoc doc,
          required List<YrsScopeItem> scope,
          required BigInt captureTimeoutMillis}) =>
      RustLib.instance.api.crateApiYrsUndoYrsUndoManagerNew(
          doc: doc, scope: scope, captureTimeoutMillis: captureTimeoutMillis);

  bool redo();

  /// Number of local stack items currently available to redo.
  BigInt redoStackLen();

  /// Equivalent of Yjs's `stopCapturing()` — forces the next mutation to
  /// start a fresh stack item rather than merging into the previous one.
  void reset();

  bool undo();

  /// Number of local stack items currently available to undo.
  ///
  /// Exposed so callers can key their own per-step state (a cursor or
  /// selection to restore, say) to an exact stack depth, rather than having to
  /// infer it from how many edits happened to merge into one item.
  BigInt undoStackLen();
}
