// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'values.dart';
import 'yrs_array.dart';
import 'yrs_text.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YrsMap>>
abstract class YrsMap implements RustOpaqueInterface {
  void clear();

  bool contains({required String key});

  void delete({required String key});

  YOutValue? get_({required String key});

  String json();

  List<String> keys();

  int length();

  void set_({required String key, required YInValue value});

  YrsArray setArray({required String key});

  YrsMap setMap({required String key});

  YrsText setText({required String key});
}
